apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - port: {{ .Values.backend.servicePort }}
      targetPort: {{ .Values.backend.port }}
